

#https->tcp, https->https
#curl https://www.example.cn:21101 -k -v
    server {
        domain str = "www.example.cn";
         domain_listen_tcp raw = r```
            address = "0.0.0.0:21101"
        ```r;
        local {
            rule raw = r```
                [[rule]]
                data= ""
                filter = "$$(.*)"
            ```r;
            proxy_pass_upstream str = "upstream5_quic";
        }
    }

#https->ssl, http->http
#curl https://www.example.cn:21102 -k -v
    server {
        domain str = "www.example.cn";
        domain_listen_ssl raw = r```
            address = "0.0.0.0:21102"
            ssl = {key = "./cert/www.example.cn.key.pem", cert = "./cert/www.example.cn.cert.pem"}
        ```r;
        domain_listen_quic raw = r```
            address = "0.0.0.0:21102"
            ssl = {key = "./cert/www.example.cn.key.pem", cert = "./cert/www.example.cn.cert.pem"}
        ```r;
        local {
            rule raw = r```
                [[rule]]
                data= ""
                filter = "$$(.*)"
            ```r;
            proxy_pass_upstream str = "upstream6_quic";
        }
    }

#https->ssl, http->https
#curl https://www.example.cn:21103 -k -v
    server {
        domain str = "www.example.cn";
        domain_listen_ssl raw = r```
            address = "0.0.0.0:21103"
            ssl = {key = "./cert/www.example.cn.key.pem", cert = "./cert/www.example.cn.cert.pem"}
        ```r;
        domain_listen_quic raw = r```
            address = "0.0.0.0:21103"
            ssl = {key = "./cert/www.example.cn.key.pem", cert = "./cert/www.example.cn.cert.pem"}
        ```r;
        local {
            rule raw = r```
                [[rule]]
                data= ""
                filter = "$$(.*)"
            ```r;
            proxy_pass_upstream str = "upstream7_quic";
        }
    }

#http->tcp, tcp->http
#curl http://www.example.cn:21104 -k -v
    server {
        domain str = "www.example.cn";

        domain_from_http_v1 raw = r```
                is_open = true
                [check_methods]
                get = true
                post = true
                put = true
                delete = true
                patch = true
                head = true
                options = true
                purge = true
        ```r;

         domain_listen_tcp raw = r```
            address = "0.0.0.0:21104"
        ```r;
        local {
            rule raw = r```
                [[rule]]
                data= ""
                filter = "$$(.*)"
            ```r;
            proxy_pass_upstream str = "upstream1_quic";
        }
    }