server {
    # $$(.*)
    domain str = "www.example.cn";
     net_server_http raw = r```
    ```r;
    domain_listen_tcp raw = r```
        address = "0.0.0.0:28100"
    ```r;
    domain_listen_ssl raw = r```
        address = "0.0.0.0:28200"
        ssl = {key = "./cert/www.example.cn.key.pem", cert = "./cert/www.example.cn.cert.pem"}
    ```r;
     domain_listen_quic raw = r```
        address = "0.0.0.0:28300"
        ssl = {key = "./cert/www.example.cn.key.pem", cert = "./cert/www.example.cn.cert.pem"}
    ```r;

    local {

     net_server_http_static window_raw = r```
        path = "C:/Users/yefy/Desktop/yefy/tools/nginx/nginx-1.18.0/html"
    ```r;
     net_server_http_static linux_raw = r```
        path = "/root/Desktop/fdisk/nginx/nginx-1.18.0/nginx/html"
    ```r;
    }
}

#curl  http://www.example.cn:23300/1.txt -v
server {
    domain str = "www.example.cn";
    net_server_http raw = r```
    ```r;

     domain_listen_tcp raw = r```
        address = "0.0.0.0:23300"
    ```r;

    local {
        net_server_http_proxy raw = r```
        ```r;
        proxy_pass_upstream str = "upstream_to_local_origin_1";
    }
}

#curl  http://www.example.cn:23301/1.txt -v
server {
    domain str = "www.example.cn";
    net_server_http raw = r```
    ```r;

     domain_listen_tcp raw = r```
        address = "0.0.0.0:23301"
    ```r;

    local {
        net_server_http_proxy raw = r```
        ```r;
        proxy_pass_tcp raw = r```
            address = "www.upstream.cn:28100"
        ```r;
    }
}


#curl  -H "upstream_domain: www.upstream.cn"  http://www.example.cn:23302/1.txt -v
server {
    domain str = "www.example.cn";
    net_server_http raw = r```
    ```r;

     domain_listen_tcp raw = r```
        address = "0.0.0.0:23302"
    ```r;

    local {
        net_server_http_proxy raw = r```
        ```r;
        proxy_pass_tcp raw = r```
            address = "${http_request_upstream_domain}:28100"
        ```r;
    }
}
