package component:server;

interface wasm-service {
    use wasm-std.{error};
    run: func(config: option<string>) -> result<error, string>;
}

world wasm-server {
    import wasm-std;
    import wasm-log;
    import wasm-store;
    import wasm-http;
    import wasm-tcp;
    export wasm-service;
}