interface wasm-std {
    use wasm-http.{response, request};
    enum error {
        //继续进行
        ok,
        //结束当前循环
        break,
        //结束所有循环
        finish,
        //错误退出请求
        error,
        //退出请求
        return,
        ext1,
        ext2,
        ext3,
    }

    anyproxy-version: func() -> result<string, string>;
    variable: func(key: string) -> result<option<string>, string>;

    in-add-headers: func(headers: list<tuple<string, string>>) -> result<_, string>;
    in-add-header: func(key: string, value: string) -> result<_, string>;
    in-del-headers: func(headers: list<string>) -> result<_, string>;
    in-del-header: func(key: string) -> result<_, string>;
    in-is-header: func(key: string) -> result<bool, string>;
    in-get-header: func(key: string) -> result<option<string>, string>;
    in-get-request: func() -> result<request, string>;
    in-body-read-exact: func() -> result<string, string>;

    out-add-headers: func(headers: list<tuple<string, string>>) -> result<_, string>;
    out-add-header: func(key: string, value: string) -> result<_, string>;
    out-del-headers: func(headers: list<string>) -> result<_, string>;
    out-del-header: func(key: string) -> result<_, string>;
    out-is-header: func(key: string) -> result<bool, string>;
    out-get-header: func(key: string) -> result<option<string>, string>;
    out-set-response: func(res: response) -> result<_, string>;
}