#最简单http router配置
net {
    #http static
    server {
        domain str = "www.example.cn";
         net_server_http raw = r```
        ```r;
        domain_listen_tcp raw = r```
            address = "0.0.0.0:19090"
        ```r;
        local {

         net_server_http_static window_raw = r```
            path = "C:/Users/yefy/Desktop/yefy/tools/nginx/nginx-1.18.0/html"
        ```r;
         net_server_http_static linux_raw = r```
            path = "/root/Desktop/fdisk/nginx/nginx-1.18.0/nginx/html"
        ```r;
        }
    }

    #http proxy配置
    server {
        domain str = "www.example.cn";

        net_server_http raw = r```
        ```r;

         domain_listen_tcp raw = r```
            address = "0.0.0.0:20201"
        ```r;


        local {
            #过期时间
            expires usize = 120;
            net_server_http_proxy raw = r```
                proxy_pass = {version = "http1.1"}
            ```r;

            proxy_pass_upstream str = "//tcp//www.upstream.cn:19090//random";
        }
    }

    #开启http_router支持
    server {
        domain str = "www.example.cn";
        net_server_http raw = r```
        ```r;
        domain_listen_tcp raw = r```
            address = "0.0.0.0:11210"
        ```r;
        local {
            name str = "local_router";
            net_server_http_router str = "anyproxy_router_test";
        }
    }
}
#curl http://www.example.cn:19090/1.txt -v -k
#curl http://www.example.cn:20201/1.txt -v -k