package component:server;

interface wasm-service {
    use wasm-std.{error};
    run: func(config: string) -> result<error, string>;
}

world wasm-server {
    import wasm-std;
    export wasm-service;
}