package component:server;

interface wasm-service {
    use wasm-std.{error};
    wasm-main: func(typ: option<s64>, config: option<string>) -> result<error, string>;
}

world wasm-server {
    import wasm-std;
    import wasm-log;
    import wasm-store;
    import wasm-http;
    import wasm-socket;
    import wasm-websocket;
    export wasm-service;
}