interface wasm-socket {
    enum socket-type {
        tcp,
        ssl,
        quic,
    }

    socket-connect: func(typ: socket-type, addr: string, ssl-domain: option<string>, timeout-ms: u64) -> result<u64, string>;
    socket-read: func(fd: u64, size: u64, timeout-ms: u64) -> result<list<u8>, string>;
    socket-read-exact: func(fd: u64, size: u64, timeout-ms: u64) -> result<list<u8>, string>;
    socket-write: func(fd: u64, data: list<u8>, timeout-ms: u64) -> result<u64, string>;
    socket-write-all: func(fd: u64, data: list<u8>, timeout-ms: u64) -> result<u64, string>;
    socket-flush: func(fd: u64, timeout-ms: u64) -> result<_, string>;
    socket-close: func(fd: u64, timeout-ms: u64) -> result<_, string>;
}