#最简单http proxy配置
net {
    #window路径
    proxy_cache window_raw = r```
        is_open = true
        name = "proxy_cache_1"
        path = "C:/Users/yefy/Desktop/proxy_cache/proxy_cache_1"
        levels = "2:2"
        max_size = 0
    ```r;
    #linux路径
    proxy_cache linux_raw = r```
            is_open = true
            name = "proxy_cache_1"
            path = "/root/Desktop/proxy_cache/proxy_cache_1"
            levels = "2:2"
            max_size = 0
        ```r;

    proxy_cache_name strs = proxy_cache_1;
    proxy_request_slice usize = 3;
    proxy_cache_key str = "${http_request_method}${http_request_domain}${http_request_port}${http_request_uri}";



    #http static
    server {
        domain str = "www.example.cn";
         net_server_http raw = r```
        ```r;
        domain_listen_tcp raw = r```
            address = "0.0.0.0:19090"
        ```r;
        local {

         net_server_http_static window_raw = r```
            path = "C:/Users/yefy/Desktop/yefy/tools/nginx/nginx-1.18.0/html"
        ```r;
         net_server_http_static linux_raw = r```
            path = "/root/Desktop/fdisk/nginx/nginx-1.18.0/nginx/html"
        ```r;
        }
    }

    #http proxy配置
    server {
        domain str = "www.example.cn";

        net_server_http raw = r```
        ```r;

         domain_listen_tcp raw = r```
            address = "0.0.0.0:20201"
        ```r;


        local {
            #过期时间
            expires usize = 120;
            #添加这个配置才能支持purge
            proxy_cache_purge bool = true;
            net_server_http_proxy raw = r```
                proxy_pass = {version = "http1.1"}
            ```r;

            proxy_pass_upstream str = "//tcp//www.upstream.cn:19090//random";
        }
    }
}
#请求文件并缓存
#curl http://www.example.cn:20201/1.txt -v -k
#延迟删除
#curl -H "purge:purge" http://www.example.cn:20201/purge/1.txt -v -k
#马上强制删除
#curl -H "purge:purge_force" http://www.example.cn:20201/purge/1.txt -v -k