#最简单http proxy配置
net {
    #window路径
    proxy_cache window_raw = r```
        is_open = true
        name = "proxy_cache_1"
        path = "C:/Users/yefy/Desktop/proxy_cache/proxy_cache_1"
        levels = "2:2"
        max_size = 0
    ```r;
    proxy_cache window_raw = r```
            is_open = true
            name = "proxy_cache_2"
            path = "C:/Users/yefy/Desktop/proxy_cache/proxy_cache_2"
            levels = "2:2"
            max_size = 0
        ```r;
    #linux路径
    proxy_cache linux_raw = r```
            is_open = true
            name = "proxy_cache_1"
            path = "/root/Desktop/proxy_cache/proxy_cache_1"
            levels = "2:2"
            max_size = 0
        ```r;
     proxy_cache linux_raw = r```
            is_open = true
            name = "proxy_cache_2"
            path = "/root/Desktop/proxy_cache/proxy_cache_2"
            levels = "2:2"
            max_size = 0
        ```r;

    proxy_cache_name strs = proxy_cache_1;
    proxy_request_slice usize = 3;
    proxy_cache_key str = "${http_request_method}${http_request_domain}${http_request_port}${http_request_uri}";


    #层级：main|server|local
    #热点文件配置
    proxy_hot_file raw = r```
        #是否打开
        is_open = true
        #时间间隔统计一次
        hot_interval_time = 5
        #前面多少个是热点文件
        hot_top_count = 5
        #读取多少次，才能是热点文件, 暂时不支持
        hot_read_min_count = 10
        #磁盘io达到多少后,开始迁移热点文件
        hot_io_percent = 70
        #热点文件迁移到哪里, 最好用ssd存储热点文件
        hot_proxy_cache_name = ["proxy_cache_2"]
    ```r;

    #http static
    server {
        domain str = "www.example.cn";
         net_server_http raw = r```
        ```r;
        domain_listen_tcp raw = r```
            address = "0.0.0.0:19090"
        ```r;
        local {

         net_server_http_static window_raw = r```
            path = "C:/Users/yefy/Desktop/yefy/tools/nginx/nginx-1.18.0/html"
        ```r;
         net_server_http_static linux_raw = r```
            path = "/root/Desktop/fdisk/nginx/nginx-1.18.0/nginx/html"
        ```r;
        }
    }

    #http proxy配置
    server {
        domain str = "www.example.cn";

        net_server_http raw = r```
        ```r;

         domain_listen_tcp raw = r```
            address = "0.0.0.0:20201"
        ```r;


        local {
            #过期时间
            expires usize = 120;
            net_server_http_proxy raw = r```
                proxy_pass = {version = "http1.1"}
            ```r;

            proxy_pass_upstream str = "//tcp//www.upstream.cn:19090//random";
        }
    }


#上传proxy_cache的磁盘读io占比, 上面配置hot_io_percent = 70,  这里把proxy_cache_1 读io设置成90, 开始迁移热点文件
#curl -X POST -H "Content-Type: application/json" -d '{"proxy_cache_1":90, "proxy_cache_2":0}' http://www.example.cn:11210/proxy/hot_io_percent -k -v

    #开启http_router支持
    server {
        domain str = "www.example.cn";
        net_server_http raw = r```
        ```r;
        domain_listen_tcp raw = r```
            address = "0.0.0.0:11210"
        ```r;
        local {
            name str = "local_router";
            net_server_http_router str = "";
        }
    }
}
#热点文件最好迁移到固态磁盘
#请求文件并缓存
#curl http://www.example.cn:20201/1.txt -v -k

#anyproxy.log reopen
#curl http://www.example.cn:11210/log/reopen -k -v