#最简单domain代理配置
net {
    #http static
    server {
        domain str = "www.example.cn";
         net_server_http raw = r```
        ```r;
        domain_listen_ssl raw = r```
            address = "0.0.0.0:19091"
            ssl = {key = "./cert/www.example.cn.key.pem", cert = "./cert/www.example.cn.cert.pem"}
        ```r;
        local {

         net_server_http_static window_raw = r```
            path = "C:/Users/yefy/Desktop/yefy/tools/nginx/nginx-1.18.0/html"
        ```r;
         net_server_http_static linux_raw = r```
            path = "/root/Desktop/fdisk/nginx/nginx-1.18.0/nginx/html"
        ```r;
        }
    }

    server {
        domain str = "www.example.cn";
        domain_listen_tcp raw = r```
            address = "0.0.0.0:30101"
        ```r;
        local {
            proxy_pass_upstream str = "//tcp//www.upstream.cn:19091//round_robin";
        }
    }
}
#curl https://www.example.cn:30101 -v -k