#最简单http static配置
net {
    server {
        domain str = "www.example.cn";
         net_server_http raw = r```
        ```r;
        domain_listen_tcp raw = r```
            address = "0.0.0.0:19090"
        ```r;
        local {

         net_server_http_static window_raw = r```
            path = "C:/Users/yefy/Desktop/yefy/tools/nginx/nginx-1.18.0/html"
        ```r;
         net_server_http_static linux_raw = r```
            path = "/root/Desktop/fdisk/nginx/nginx-1.18.0/nginx/html"
        ```r;
        }
    }
}
#curl http://www.example.cn:19090 -v