#最简单port代理配置
net {
    #http static
    server {
        domain str = "www.example.cn";
         net_server_http raw = r```
        ```r;
        domain_listen_tcp raw = r```
            address = "0.0.0.0:19090"
        ```r;
        local {

         net_server_http_static window_raw = r```
            path = "C:/Users/yefy/Desktop/yefy/tools/nginx/nginx-1.18.0/html"
        ```r;
         net_server_http_static linux_raw = r```
            path = "/root/Desktop/fdisk/nginx/nginx-1.18.0/nginx/html"
        ```r;
        }
    }

    server {
        domain str = "www.example.cn";
        port_listen_tcp raw = r```
            address = "0.0.0.0:30001"
        ```r;
        local {
            proxy_pass_upstream str = "//tcp//www.upstream.cn:19090//round_robin";
        }
    }
}
#curl http://www.example.cn:30001 -v