pub mod any_ebpf;
pub mod any_ebpf_core;
pub mod common;
pub mod common_core;
pub mod config_toml;
pub mod domain_core;
pub mod domain_listen_quic;
pub mod domain_listen_ssl;
pub mod domain_listen_tcp;
pub mod http;
pub mod http_access_log;
pub mod http_core;
pub mod http_core_plugin;
pub mod http_proxy_pass_quic;
pub mod http_proxy_pass_ssl;
pub mod http_proxy_pass_tcp;
pub mod http_proxy_pass_tunnel;
pub mod http_proxy_pass_tunnel2;
pub mod http_proxy_pass_upstream;
pub mod http_server_core;
pub mod http_server_core_plugin;
pub mod http_server_echo;
pub mod http_server_echo_websocket;
pub mod http_server_proxy;
pub mod http_server_proxy_websocket;
pub mod http_server_static;
pub mod http_server_static_websocket;
pub mod httplocal;
pub mod httpserver;
pub mod port_core;
pub mod port_listen_quic;
pub mod port_listen_ssl;
pub mod port_listen_tcp;
pub mod socket;
pub mod socket_quic;
pub mod socket_tcp;
pub mod stream_stream_cache;
pub mod stream_stream_memory;
pub mod stream_stream_tmp_file;
pub mod stream_stream_write;
pub mod tunnel;
pub mod tunnel2;
pub mod tunnel2_core;
pub mod tunnel_core;
pub mod upstream;
pub mod upstream_block;
pub mod upstream_core;
pub mod upstream_core_plugin;
pub mod upstream_proxy_pass_quic;
pub mod upstream_proxy_pass_ssl;
pub mod upstream_proxy_pass_tcp;
pub mod upstream_proxy_pass_tunnel;
pub mod upstream_proxy_pass_tunnel2;

pub const MODULE_TYPE_HTTP: usize = 1 << 0;
pub const MODULE_TYPE_EBPF: usize = 1 << 1;
pub const MODULE_TYPE_UPSTREAM: usize = 1 << 2;
pub const MODULE_TYPE_COMMON: usize = 1 << 3;
pub const MODULE_TYPE_TUNNEL: usize = 1 << 4;
pub const MODULE_TYPE_TUNNEL2: usize = 1 << 5;
pub const MODULE_TYPE_SOCKET: usize = 1 << 6;

pub const CMD_CONF_TYPE_MAIN: usize = 1 << 0;
pub const CMD_CONF_TYPE_SERVER: usize = 1 << 1;
pub const CMD_CONF_TYPE_LOCAL: usize = 1 << 2;
